-------------------------------------------------------------------------------
Test set: io.cloudboost.CloudFileTest
-------------------------------------------------------------------------------
Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 14.044 sec <<< FAILURE!
shouldSaveFileAndFetchIt(io.cloudboost.CloudFileTest)  Time elapsed: 1.428 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Bad Request
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudFileTest$4$1.done(CloudFileTest.java:244)
	at io.cloudboost.CloudFile$1.done(CloudFile.java:457)
	at io.cloudboost.CloudQuery.find(CloudQuery.java:1379)
	at io.cloudboost.CloudFile.fetch(CloudFile.java:453)
	at io.cloudboost.CloudFileTest$4.done(CloudFileTest.java:238)
	at io.cloudboost.CloudFile.save(CloudFile.java:338)
	at io.cloudboost.CloudFileTest.shouldSaveFileAndFetchIt(CloudFileTest.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

