-------------------------------------------------------------------------------
Test set: io.cloudboost.CreateTableTest
-------------------------------------------------------------------------------
Tests run: 34, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 69.082 sec <<< FAILURE!
createTableCustom2(io.cloudboost.CreateTableTest)  Time elapsed: 3.778 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Table already exists.
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CreateTableTest$19$1$1.done(CreateTableTest.java:817)
	at io.cloudboost.CloudTable.save(CloudTable.java:372)
	at io.cloudboost.CreateTableTest$19$1.done(CreateTableTest.java:811)
	at io.cloudboost.CloudTable.save(CloudTable.java:369)
	at io.cloudboost.CreateTableTest$19.done(CreateTableTest.java:798)
	at io.cloudboost.CloudTable.save(CloudTable.java:369)
	at io.cloudboost.CreateTableTest.createTableCustom2(CreateTableTest.java:794)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

