-------------------------------------------------------------------------------
Test set: io.cloudboost.CloudQueueTest
-------------------------------------------------------------------------------
Tests run: 40, Failures: 10, Errors: 1, Skipped: 0, Time elapsed: 33.336 sec <<< FAILURE!
pullMessageAfterTimeout(io.cloudboost.CloudQueueTest)  Time elapsed: 0.654 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Not Found
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudQueueTest$36$1.done(CloudQueueTest.java:1304)
	at io.cloudboost.CloudQueue.pull(CloudQueue.java:803)
	at io.cloudboost.CloudQueueTest$36.done(CloudQueueTest.java:1299)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.CloudQueueTest.pullMessageAfterTimeout(CloudQueueTest.java:1291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

pushAndPullSameMessage(io.cloudboost.CloudQueueTest)  Time elapsed: 0.66 sec  <<< FAILURE!
junit.framework.ComparisonFailure: null expected:<[Not Found]> but was:<[Object Validation Failure]>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at io.cloudboost.CloudQueueTest$7$1.done(CloudQueueTest.java:194)
	at io.cloudboost.CloudQueue.pull(CloudQueue.java:803)
	at io.cloudboost.CloudQueueTest$7.done(CloudQueueTest.java:188)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.CloudQueueTest.pushAndPullSameMessage(CloudQueueTest.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

shouldPeekTwoMessages(io.cloudboost.CloudQueueTest)  Time elapsed: 1.06 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Not Found
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudQueueTest$12$1$1.done(CloudQueueTest.java:446)
	at io.cloudboost.CloudQueue.peek(CloudQueue.java:232)
	at io.cloudboost.CloudQueueTest$12$1.done(CloudQueueTest.java:441)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.CloudQueueTest$12.done(CloudQueueTest.java:437)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.CloudQueueTest.shouldPeekTwoMessages(CloudQueueTest.java:429)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

getMessagesInFIFO(io.cloudboost.CloudQueueTest)  Time elapsed: 1.39 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Not Found
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudQueueTest$10$1$1.done(CloudQueueTest.java:320)
	at io.cloudboost.CloudQueue.pull(CloudQueue.java:803)
	at io.cloudboost.CloudQueueTest$10$1.done(CloudQueueTest.java:311)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.CloudQueueTest$10.done(CloudQueueTest.java:301)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.CloudQueueTest.getMessagesInFIFO(CloudQueueTest.java:292)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

pullMessageAfterDelay(io.cloudboost.CloudQueueTest)  Time elapsed: 2.677 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Not Found
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudQueueTest$35$1.done(CloudQueueTest.java:1268)
	at io.cloudboost.CloudQueue.pull(CloudQueue.java:803)
	at io.cloudboost.CloudQueueTest$35.done(CloudQueueTest.java:1263)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.CloudQueueTest.pullMessageAfterDelay(CloudQueueTest.java:1247)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

shouldPeek(io.cloudboost.CloudQueueTest)  Time elapsed: 0.672 sec  <<< FAILURE!
junit.framework.ComparisonFailure: null expected:<[Not Found]> but was:<[Object Validation Failure]>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at io.cloudboost.CloudQueueTest$9$1.done(CloudQueueTest.java:270)
	at io.cloudboost.CloudQueue.peek(CloudQueue.java:232)
	at io.cloudboost.CloudQueueTest$9.done(CloudQueueTest.java:265)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.CloudQueueTest.shouldPeek(CloudQueueTest.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

shouldPeekTwo(io.cloudboost.CloudQueueTest)  Time elapsed: 1.028 sec  <<< FAILURE!
junit.framework.ComparisonFailure: null expected:<[Not Found]> but was:<[Object Validation Failure]>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at io.cloudboost.CloudQueueTest$11$1$1.done(CloudQueueTest.java:396)
	at io.cloudboost.CloudQueue.peek(CloudQueue.java:232)
	at io.cloudboost.CloudQueueTest$11$1.done(CloudQueueTest.java:387)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.CloudQueueTest$11.done(CloudQueueTest.java:377)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.CloudQueueTest.shouldPeekTwo(CloudQueueTest.java:368)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

shouldPullTwo(io.cloudboost.CloudQueueTest)  Time elapsed: 1.121 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Not Found
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudQueueTest$13$1$1.done(CloudQueueTest.java:498)
	at io.cloudboost.CloudQueue.pull(CloudQueue.java:803)
	at io.cloudboost.CloudQueueTest$13$1.done(CloudQueueTest.java:489)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.CloudQueueTest$13.done(CloudQueueTest.java:479)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.CloudQueueTest.shouldPullTwo(CloudQueueTest.java:470)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

shoulNotPullSameMessageTwice(io.cloudboost.CloudQueueTest)  Time elapsed: 0.92 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Not Found
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudQueueTest$16$1.done(CloudQueueTest.java:597)
	at io.cloudboost.CloudQueue.pull(CloudQueue.java:803)
	at io.cloudboost.CloudQueueTest$16.done(CloudQueueTest.java:591)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.CloudQueueTest.shoulNotPullSameMessageTwice(CloudQueueTest.java:584)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

shouldNotSubscribeInvalidUrl(io.cloudboost.CloudQueueTest)  Time elapsed: 0.329 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Should not save subscriber with invalid url
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudQueueTest$25.done(CloudQueueTest.java:904)
	at io.cloudboost.CloudQueue.addSubscriber(CloudQueue.java:518)
	at io.cloudboost.CloudQueueTest.shouldNotSubscribeInvalidUrl(CloudQueueTest.java:897)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

refreshMessageTimeoutPulledMessage(io.cloudboost.CloudQueueTest)  Time elapsed: 0.669 sec  <<< ERROR!
java.lang.NullPointerException
	at io.cloudboost.CloudQueueTest$37$1.done(CloudQueueTest.java:1359)
	at io.cloudboost.CloudQueue.pull(CloudQueue.java:803)
	at io.cloudboost.CloudQueueTest$37.done(CloudQueueTest.java:1355)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.CloudQueueTest.refreshMessageTimeoutPulledMessage(CloudQueueTest.java:1347)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

