-------------------------------------------------------------------------------
Test set: io.cloudboost.QueueTest
-------------------------------------------------------------------------------
Tests run: 40, Failures: 12, Errors: 1, Skipped: 0, Time elapsed: 40.811 sec <<< FAILURE!
pullMessageAfterTimeout(io.cloudboost.QueueTest)  Time elapsed: 1.08 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Not Found
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.QueueTest$36$1.done(QueueTest.java:1166)
	at io.cloudboost.CloudQueue.pull(CloudQueue.java:803)
	at io.cloudboost.QueueTest$36.done(QueueTest.java:1161)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.QueueTest.pullMessageAfterTimeout(QueueTest.java:1153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

pushAndPullSameMessage(io.cloudboost.QueueTest)  Time elapsed: 0.452 sec  <<< FAILURE!
junit.framework.ComparisonFailure: null expected:<[Not Found]> but was:<[Object Validation Failure]>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at io.cloudboost.QueueTest$7.done(QueueTest.java:184)
	at io.cloudboost.CloudQueue.pull(CloudQueue.java:803)
	at io.cloudboost.QueueTest.pushAndPullSameMessage(QueueTest.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

shouldPeekTwoMessages(io.cloudboost.QueueTest)  Time elapsed: 1.75 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Not Found
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.QueueTest$12$1$1.done(QueueTest.java:417)
	at io.cloudboost.CloudQueue.peek(CloudQueue.java:232)
	at io.cloudboost.QueueTest$12$1.done(QueueTest.java:412)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.QueueTest$12.done(QueueTest.java:408)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.QueueTest.shouldPeekTwoMessages(QueueTest.java:400)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

getMessagesInFIFO(io.cloudboost.QueueTest)  Time elapsed: 1.709 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Not Found
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.QueueTest$10$1$1.done(QueueTest.java:291)
	at io.cloudboost.CloudQueue.pull(CloudQueue.java:803)
	at io.cloudboost.QueueTest$10$1.done(QueueTest.java:282)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.QueueTest$10.done(QueueTest.java:272)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.QueueTest.getMessagesInFIFO(QueueTest.java:263)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

shouldDeleteQueueByName(io.cloudboost.QueueTest)  Time elapsed: 0.521 sec  <<< FAILURE!
junit.framework.AssertionFailedError: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.QueueTest$27.done(QueueTest.java:871)
	at io.cloudboost.CloudQueue.deleteQueue(CloudQueue.java:767)
	at io.cloudboost.CloudQueue.deleteQueue(CloudQueue.java:859)
	at io.cloudboost.QueueTest.shouldDeleteQueueByName(QueueTest.java:866)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

pullMessageAfterDelay(io.cloudboost.QueueTest)  Time elapsed: 3.249 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Not Found
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.QueueTest$35$1.done(QueueTest.java:1130)
	at io.cloudboost.CloudQueue.pull(CloudQueue.java:803)
	at io.cloudboost.QueueTest$35.done(QueueTest.java:1125)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.QueueTest.pullMessageAfterDelay(QueueTest.java:1109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

shouldGetQueue(io.cloudboost.QueueTest)  Time elapsed: 0.79 sec  <<< FAILURE!
junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at io.cloudboost.QueueTest$30.done(QueueTest.java:969)
	at io.cloudboost.CloudQueue.get(CloudQueue.java:914)
	at io.cloudboost.QueueTest.shouldGetQueue(QueueTest.java:959)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

shouldPeek(io.cloudboost.QueueTest)  Time elapsed: 0.366 sec  <<< FAILURE!
junit.framework.ComparisonFailure: null expected:<[Not Found]> but was:<[Object Validation Failure]>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at io.cloudboost.QueueTest$9.done(QueueTest.java:246)
	at io.cloudboost.CloudQueue.peek(CloudQueue.java:232)
	at io.cloudboost.QueueTest.shouldPeek(QueueTest.java:241)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

shouldPeekTwo(io.cloudboost.QueueTest)  Time elapsed: 1.341 sec  <<< FAILURE!
junit.framework.ComparisonFailure: null expected:<[Not Found]> but was:<[Object Validation Failure]>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at io.cloudboost.QueueTest$11$1$1.done(QueueTest.java:367)
	at io.cloudboost.CloudQueue.peek(CloudQueue.java:232)
	at io.cloudboost.QueueTest$11$1.done(QueueTest.java:358)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.QueueTest$11.done(QueueTest.java:348)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.QueueTest.shouldPeekTwo(QueueTest.java:339)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

shouldPullTwo(io.cloudboost.QueueTest)  Time elapsed: 0.319 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Not Found
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.QueueTest$13.done(QueueTest.java:450)
	at io.cloudboost.CloudQueue.pull(CloudQueue.java:803)
	at io.cloudboost.QueueTest.shouldPullTwo(QueueTest.java:441)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

shoulNotPullSameMessageTwice(io.cloudboost.QueueTest)  Time elapsed: 0.719 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Not Found
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.QueueTest$16$1.done(QueueTest.java:538)
	at io.cloudboost.CloudQueue.pull(CloudQueue.java:803)
	at io.cloudboost.QueueTest$16.done(QueueTest.java:532)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.QueueTest.shoulNotPullSameMessageTwice(QueueTest.java:525)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

shouldNotSubscribeInvalidUrl(io.cloudboost.QueueTest)  Time elapsed: 0.492 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Should not save subscriber with invalid url
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.QueueTest$25.done(QueueTest.java:807)
	at io.cloudboost.CloudQueue.addSubscriber(CloudQueue.java:518)
	at io.cloudboost.QueueTest.shouldNotSubscribeInvalidUrl(QueueTest.java:800)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

refreshMessageTimeoutPulledMessage(io.cloudboost.QueueTest)  Time elapsed: 0.781 sec  <<< ERROR!
java.lang.NullPointerException
	at io.cloudboost.QueueTest$37$1.done(QueueTest.java:1221)
	at io.cloudboost.CloudQueue.pull(CloudQueue.java:803)
	at io.cloudboost.QueueTest$37.done(QueueTest.java:1217)
	at io.cloudboost.CloudQueue.push(CloudQueue.java:720)
	at io.cloudboost.QueueTest.refreshMessageTimeoutPulledMessage(QueueTest.java:1209)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)

