<?xml version="1.0" encoding="UTF-8" ?>
<testsuite tests="45" failures="29" name="io.cloudboost.object.CloudObjectTest" time="10.102" errors="0" skipped="0">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="C:\Program Files\jdk1.8.0_05\jre\bin"/>
    <property name="java.vm.version" value="25.5-b02"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="maven.multiModuleProjectDirectory" value="E:\Engineer\programming\projects\javaSDK\git_repo"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=";"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) Client VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.script" value=""/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value=""/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="E:\Engineer\programming\projects\javaSDK\git_repo"/>
    <property name="java.runtime.version" value="1.8.0_05-b13"/>
    <property name="java.awt.graphicsenv" value="sun.awt.Win32GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="C:\Program Files\jdk1.8.0_05\jre\lib\endorsed"/>
    <property name="os.arch" value="x86"/>
    <property name="java.io.tmpdir" value="C:\Users\new\AppData\Local\Temp\"/>
    <property name="line.separator" value="
"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="user.variant" value=""/>
    <property name="os.name" value="Windows 8.1"/>
    <property name="classworlds.conf" value="C:\Program Files (x86)\apache-maven-3.3.3\bin\..\bin\m2.conf"/>
    <property name="sun.jnu.encoding" value="Cp1252"/>
    <property name="java.library.path" value="C:\Program Files\jdk1.8.0_05\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\ProgramData\Oracle\Java\javapath;C:\oraclexe\app\oracle\product\11.2.0\server\bin;;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\GNU\GnuPG\pub;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files\MySQL\MySQL Server 5.6\bin;C:\Program Files (x86)\apache-ant-1.9.6\bin;C:\Program Files\jdk1.8.0_05\bin;E:\Engineer\eclipse\android-sdk-windows\tools;E:\Engineer\eclipse\android-sdk-windows\platform-tools;C:\Program Files\jdk1.8.0_05\bin;C:\Program Files\MongoDB\Server\3.0\bin;E:\Engineer\eclipse\eclipse;E:\Engineer\eclipse\myeclipse;C:\Program Files (x86)\apache-maven-3.3.3\bin;C:\Program Files (x86)\GNU\GnuPG;C:\Program Files\openssl-0.9.8k_X64\bin;C:\Program Files\nodejs;C:\Users\new\AppData\Roaming\npm;C:\Program Files\Wireshark;."/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot Client Compiler"/>
    <property name="os.version" value="6.3"/>
    <property name="user.home" value="C:\Users\new"/>
    <property name="user.timezone" value="Africa/Nairobi"/>
    <property name="java.awt.printerjob" value="sun.awt.windows.WPrinterJob"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="file.encoding" value="Cp1252"/>
    <property name="user.name" value="new"/>
    <property name="java.class.path" value="C:\Program Files (x86)\apache-maven-3.3.3\bin\..\boot\plexus-classworlds-2.5.2.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="32"/>
    <property name="java.home" value="C:\Program Files\jdk1.8.0_05\jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher test"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="en"/>
    <property name="awt.toolkit" value="sun.awt.windows.WToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_05"/>
    <property name="java.ext.dirs" value="C:\Program Files\jdk1.8.0_05\jre\lib\ext;C:\Windows\Sun\Java\lib\ext"/>
    <property name="sun.boot.class.path" value="C:\Program Files\jdk1.8.0_05\jre\lib\resources.jar;C:\Program Files\jdk1.8.0_05\jre\lib\rt.jar;C:\Program Files\jdk1.8.0_05\jre\lib\sunrsasign.jar;C:\Program Files\jdk1.8.0_05\jre\lib\jsse.jar;C:\Program Files\jdk1.8.0_05\jre\lib\jce.jar;C:\Program Files\jdk1.8.0_05\jre\lib\charsets.jar;C:\Program Files\jdk1.8.0_05\jre\lib\jfr.jar;C:\Program Files\jdk1.8.0_05\jre\classes"/>
    <property name="sun.stderr.encoding" value="cp437"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="C:\Program Files (x86)\apache-maven-3.3.3\bin\.."/>
    <property name="file.separator" value="\"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.stdout.encoding" value="cp437"/>
    <property name="sun.desktop" value="windows"/>
    <property name="sun.cpu.isalist" value="pentium_pro+mmx pentium_pro pentium+mmx pentium i486 i386 i86"/>
  </properties>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="createNotice" time="2.997"/>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="updateAfterSave" time="0.005">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$9.done(CloudObjectTest.java:219)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.updateAfterSave(CloudObjectTest.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldUnsetField" time="0.002">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$41.done(CloudObjectTest.java:1021)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.shouldUnsetField(CloudObjectTest.java:1016)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldNotSetId" time="0"/>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="saveArray" time="0.002">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$11.done(CloudObjectTest.java:269)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.saveArray(CloudObjectTest.java:265)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="deleteAfterSave" time="0.002">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$10.done(CloudObjectTest.java:243)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.deleteAfterSave(CloudObjectTest.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldGiveErrorWhenWrongDataIsPutInNumberField" time="0.001"/>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldStopListening" time="1.003">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$30.done(CloudObjectTest.java:694)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.shouldStopListening(CloudObjectTest.java:689)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldFetchCloudObject" time="0.002">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$39.done(CloudObjectTest.java:980)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.shouldFetchCloudObject(CloudObjectTest.java:975)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="keepRelationIntact" time="0.001">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$18.done(CloudObjectTest.java:416)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.keepRelationIntact(CloudObjectTest.java:412)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="saveArrayOfGeoPoint" time="0"/>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="deleteObjectNotice" time="2.004">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$32.done(CloudObjectTest.java:757)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.deleteObjectNotice(CloudObjectTest.java:753)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="saveWrongRelation" time="0.002"/>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldSaveListNumberList" time="0.003">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at io.cloudboost.object.CloudObjectTest$44.done(CloudObjectTest.java:1075)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.shouldSaveListNumberList(CloudObjectTest.java:1071)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="saveArrayOfCloudObject" time="0.003">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$22.done(CloudObjectTest.java:515)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.saveArrayOfCloudObject(CloudObjectTest.java:511)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="updateListAfterSave" time="0.004">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$23.done(CloudObjectTest.java:545)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.updateListAfterSave(CloudObjectTest.java:541)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="updateObjectNotice" time="0.008">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$28.done(CloudObjectTest.java:645)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.updateObjectNotice(CloudObjectTest.java:641)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="createObjectNotice" time="0.004">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$25.done(CloudObjectTest.java:608)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.createObjectNotice(CloudObjectTest.java:604)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldSaveGeoPointList" time="0.003">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at io.cloudboost.object.CloudObjectTest$43.done(CloudObjectTest.java:1061)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.shouldSaveGeoPointList(CloudObjectTest.java:1057)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="saveArrayWithJSONObject" time="0.002">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$13.done(CloudObjectTest.java:312)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.saveArrayWithJSONObject(CloudObjectTest.java:308)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="saveARelationWithRelate" time="0.002">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$16.done(CloudObjectTest.java:364)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.saveARelationWithRelate(CloudObjectTest.java:360)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="saveRelationWithRelate" time="0.002">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$17.done(CloudObjectTest.java:388)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.saveRelationWithRelate(CloudObjectTest.java:384)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="saveRelationWithVersion" time="0.001"/>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="SaveData" time="0.001">
    <failure message="Failed to save data" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Failed to save data
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$3.done(CloudObjectTest.java:78)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.SaveData(CloudObjectTest.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="saveJSON" time="0"/>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldNotSaveAnArrayOfDifferentObjects" time="0.002">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$46.done(CloudObjectTest.java:1123)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.shouldNotSaveAnArrayOfDifferentObjects(CloudObjectTest.java:1118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldNotAllowMultipleDataTypesInArray" time="0.001"/>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldNotSaveDupRelationInUniqueFields" time="0.001"/>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldNotDupValuesInListAfterUpdate" time="0.001">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$45.done(CloudObjectTest.java:1095)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.shouldNotDupValuesInListAfterUpdate(CloudObjectTest.java:1090)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="ShouldNotSaveWithoutRequiredColumn" time="0.001"/>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldNotSaveRelationWhenSchemaOfRelationObjectIsWrong" time="0.002"/>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="ShouldNotSaveStringIntoDate" time="0.001"/>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldAlertOnMultipleEvents" time="2.004">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$38.done(CloudObjectTest.java:931)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.shouldAlertOnMultipleEvents(CloudObjectTest.java:926)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="saveArrayWithWrongDataType" time="0.003"/>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldNotUpdateCreatedAtOnUpdate" time="0.004">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$50.done(CloudObjectTest.java:1230)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.shouldNotUpdateCreatedAtOnUpdate(CloudObjectTest.java:1225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldUpdateVersionOnUpdate" time="0.005">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$8.done(CloudObjectTest.java:186)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.shouldUpdateVersionOnUpdate(CloudObjectTest.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="saveEmptyArrayOfCloudObject" time="0.003">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$21.done(CloudObjectTest.java:486)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.saveEmptyArrayOfCloudObject(CloudObjectTest.java:482)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldAlertOnAllThreeEvents" time="2.003">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$36.done(CloudObjectTest.java:844)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.shouldAlertOnAllThreeEvents(CloudObjectTest.java:839)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldSaveRequiredNumberAs0" time="0.002">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at io.cloudboost.object.CloudObjectTest$40.done(CloudObjectTest.java:1005)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.shouldSaveRequiredNumberAs0(CloudObjectTest.java:1001)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="ShouldNotSaveWithWrongDataType" time="0.003"/>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="saveAnEmptyArrayOfCloudObject" time="0.002">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$20.done(CloudObjectTest.java:460)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.saveAnEmptyArrayOfCloudObject(CloudObjectTest.java:456)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="ShouldNotSaveDuplicateValue" time="0.003">
    <failure message="Should save the data" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Should save the data
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$7.done(CloudObjectTest.java:172)
	at io.cloudboost.CloudObject.save(CloudObject.java:885)
	at io.cloudboost.object.CloudObjectTest.ShouldNotSaveDuplicateValue(CloudObjectTest.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="shouldRejectWrongEventType" time="0.001"/>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="saveAndDeleteArrayOfCloudObject" time="0.003">
    <failure type="junit.framework.AssertionFailedError:">junit.framework.AssertionFailedError: null
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.object.CloudObjectTest$33.done(CloudObjectTest.java:790)
	at io.cloudboost.CloudObject.saveAll(CloudObject.java:981)
	at io.cloudboost.object.CloudObjectTest.saveAndDeleteArrayOfCloudObject(CloudObjectTest.java:786)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
  </testcase>
  <testcase classname="io.cloudboost.object.CloudObjectTest" name="saveCloudObjectAsRelation" time="0.003"/>
</testsuite>